### ISSUE TITLE
Please add enso for 3.60 too.

### ISSUE THREAD

**Issue by pettiagalla** [ONElua/36XUDHelper#1]
Please add enso for 3.60 too.
https://github.com/henkaku/enso/releases
I think TheFloW's enso is for 3.65.
https://github.com/TheOfficialFloW/enso/commit/6a0f8ddabc0e2f66422ded6f69e0387dce5b5855

**Comment by ONElua** [comment]
Do you get an error with Enso 1.1 from flow?

**Comment by pettiagalla** [comment]
Yes. I get the error message "Failed to load kernel module" in 3.60.

**Comment by ONElua** [comment]
ok
 wait...
EDIT: Please try again with 1.02

**Comment by pettiagalla** [comment]
Thanks! It works fine.
